  # Azure Pipelines YAML file for Angular-Python Application

parameters:
- name: gitUsername
  type: string
  default: AishwaryaaRaghuraman
- name: repoName
  type: string
  default: angular_python
- name: branchName
  type: string
  default: main

trigger:
- main

pool: Default


steps:
- script: echo "Git Clone"
  displayName: 'Git Clone'
  env:
    GIT_USERNAME: $(gitUsername)
    REPO_NAME: $(repoName)
    BRANCH_NAME: $(branchName)
  continueOnError: false
 
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js 16.x'

- script: |
    echo Starting the build
    cd frontend/
    npm install -g @angular/cli
    npm install
    ng build --prod    
  displayName: 'Build with Angular'


- script: |
    echo Starting the build
    cd backend/
    python --version
    python -m venv venv
    .\venv\Scripts\activate 
    pip install -r requirements.txt
  displayName: 'Build with Python'


- script: |
    echo "Running SonarQube Scan"
    sonar-scanner.bat -D"sonar.projectKey=$(projectkey)" -D"sonar.sources=." -D"sonar.host.url=$(SONAR_URL)" -D"sonar.token=$(SONAR_TOKEN)" 
    displayName: 'Run SonarQube Scanning'

- script: |
    # Your deployment script to start the Python backend server here
    cd backend/
    python manage.py recreate_db
    python manage.py runserver
  displayName: 'Start Python Backend Server'

# - task: ArchiveFiles@2
#   displayName: 'Archive files'
#   inputs:
#           rootFolderOrFile: '$(System.DefaultWorkingDirectory)/'
#           includeRootFolder: false
#           archiveType: zip
#           archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
#           replaceExistingArchive: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
    artifactName: 'angular-app'
    publishLocation: 'Container'